# Generated by Django 2.0.4 on 2018-05-31 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('urgencia', models.CharField(max_length=1)),
                ('material', models.ManyToManyField(to='GPI.Materiales')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPI.Obra')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('rut', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('GPI.myuser',),
        ),
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('GPI.myuser',),
        ),
        migrations.CreateModel(
            name='EncargadoCompras',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('GPI.myuser',),
        ),
        migrations.CreateModel(
            name='TrabajadorObra',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('GPI.myuser',),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitudmaterial',
            field=models.ManyToManyField(to='GPI.SolicitudMaterial'),
        ),
        migrations.AddField(
            model_name='materiales',
            name='obra',
            field=models.ManyToManyField(to='GPI.Obra'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='trabajadorobra',
            field=models.ManyToManyField(to='GPI.TrabajadorObra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='encargadocompras',
            field=models.ManyToManyField(to='GPI.EncargadoCompras'),
        ),
        migrations.AddField(
            model_name='obra',
            name='bodeguero',
            field=models.ManyToManyField(to='GPI.Bodeguero'),
        ),
        migrations.AddField(
            model_name='obra',
            name='trabajadorobra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPI.TrabajadorObra'),
        ),
    ]
