# Generated by Django 2.0.3 on 2018-05-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GPI.Usuario')),
                ('nombre', models.CharField(max_length=50)),
            ],
            bases=('GPI.usuario',),
        ),
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GPI.Usuario')),
                ('nombre', models.CharField(max_length=50)),
            ],
            bases=('GPI.usuario',),
        ),
        migrations.CreateModel(
            name='EncargadoCompras',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GPI.Usuario')),
                ('nombre', models.CharField(max_length=50)),
            ],
            bases=('GPI.usuario',),
        ),
        migrations.CreateModel(
            name='TrabajadorObra',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GPI.Usuario')),
                ('nombre', models.CharField(max_length=50)),
            ],
            bases=('GPI.usuario',),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitudmaterial',
            field=models.ManyToManyField(to='GPI.SolicitudMaterial'),
        ),
        migrations.AddField(
            model_name='materiales',
            name='obra',
            field=models.ManyToManyField(to='GPI.Obra'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='bodeguero',
            field=models.ManyToManyField(to='GPI.Bodeguero'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='trabajadorobra',
            field=models.ManyToManyField(to='GPI.TrabajadorObra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='encargadocompras',
            field=models.ManyToManyField(to='GPI.EncargadoCompras'),
        ),
        migrations.AddField(
            model_name='obra',
            name='trabajadorobra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPI.TrabajadorObra'),
        ),
    ]
