# Generated by Django 2.0.4 on 2018-04-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_interno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=15, null=True, verbose_name='RUT')),
                ('correo', models.EmailField(blank=True, max_length=15, null=True, verbose_name='Correo electronico')),
            ],
        ),
    ]
